@startuml

class Jugador{
}

class Celda{
}


class Mineral extends Recurso{
}


class Lana extends Recurso{
}


class Madera extends Recurso{
}

class Ladrillo extends Recurso{
}


class Grano extends Recurso{
}


class Carta{
}


class Construible extends Carta{
}

class Desarrollable extends Carta{
}


class Mapa{
}




class Ficha{
}


class Camino extends Ficha{
}

class Poblado extends Ficha{
}


class Ciudad extends Ficha{
}


Jugador -> Mapa
Ficha ---> Mapa
Mapa o- Celda
Recurso <- Jugador
Carta <- Jugador



@enduml