@startuml


class Construccion{
    - jugador: Jugador

    + generarSegunHexagono(hexagono:Hexagono, numDado:int)
    + {abstract} agregarJugador(listaVictimas : List<Jugador>)
    + {abstract} generarSegunVertice(dato: int) : Recurso
}


class Ciudad extends Construccion {
    +agregarJugador(listaVictimas : List<Jugador>)
    +generarSegunVertice(dato: int) : Recurso
}


class ConstruccionNula extends Construccion{
    +agregarJugador(listaVictimas : List<Jugador>)
    +generarSegunVertice(dato: int) : Recurso
}

class Poblado extends Construccion{
    +agregarJugador(listaVictimas : List<Jugador>)
    +generarSegunVertice(dato: int) : Recurso
}


class Carretera extends Construccion{
    +agregarJugador(listaVictimas : List<Jugador>)
    +generarSegunVertice(dato: int) : Recurso

}


class Jugador{
 +construir(vertice:Vertice, construccion:Construccion)
 +robarAR(victima:Jugador)
 +recibirRecurso(recurso:Recurso)
 +entregarRecursoA(ladron:Jugador)
}


Jugador "1" o-- "*" Construccion

@enduml